src/java/controladores/TipoDocumentoController.java
package controladores;

import entidades.TipoDocumento;
import controladores.util.JsfUtil;
import controladores.util.JsfUtil.PersistAction;
import facades.TipoDocumentoFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("tipoDocumentoController")
@SessionScoped
public class TipoDocumentoController implements Serializable {

    @EJB
    private facades.TipoDocumentoFacade ejbFacade;
    private List<TipoDocumento> items = null;
    private TipoDocumento selected;

    public TipoDocumentoController() {
    }

    public TipoDocumento getSelected() {
        return selected;
    }

    public void setSelected(TipoDocumento selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private TipoDocumentoFacade getFacade() {
        return ejbFacade;
    }

    public TipoDocumento prepareCreate() {
        selected = new TipoDocumento();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("TipoDocumentoCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("TipoDocumentoUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("TipoDocumentoDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<TipoDocumento> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public TipoDocumento getTipoDocumento(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<TipoDocumento> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<TipoDocumento> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = TipoDocumento.class)
    public static class TipoDocumentoControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            TipoDocumentoController controller = (TipoDocumentoController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "tipoDocumentoController");
            return controller.getTipoDocumento(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof TipoDocumento) {
                TipoDocumento o = (TipoDocumento) object;
                return getStringKey(o.getIdentificador());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), TipoDocumento.class.getName()});
                return null;
            }
        }

    }

}

web/vistas/tipoDocumento/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="TipoDocumentoCreateDlg" widgetVar="TipoDocumentoCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateTipoDocumentoTitle}">
            <h:form id="TipoDocumentoCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{tipoDocumentoController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateTipoDocumentoLabel_identificador}" for="identificador" />
                        <p:inputText id="identificador" value="#{tipoDocumentoController.selected.identificador}" title="#{bundle.CreateTipoDocumentoTitle_identificador}" required="true" requiredMessage="#{bundle.CreateTipoDocumentoRequiredMessage_identificador}"/>
                        <p:outputLabel value="#{bundle.CreateTipoDocumentoLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{tipoDocumentoController.selected.nombre}" title="#{bundle.CreateTipoDocumentoTitle_nombre}" required="true" requiredMessage="#{bundle.CreateTipoDocumentoRequiredMessage_nombre}"/>
                        <p:outputLabel value="#{bundle.CreateTipoDocumentoLabel_creditos}" for="creditos" />
                        <p:inputText id="creditos" value="#{tipoDocumentoController.selected.creditos}" title="#{bundle.CreateTipoDocumentoTitle_creditos}" required="true" requiredMessage="#{bundle.CreateTipoDocumentoRequiredMessage_creditos}"/>
                        <p:outputLabel value="#{bundle.CreateTipoDocumentoLabel_maxCreditos}" for="maxCreditos" />
                        <p:inputText id="maxCreditos" value="#{tipoDocumentoController.selected.maxCreditos}" title="#{bundle.CreateTipoDocumentoTitle_maxCreditos}" />
                        <p:outputLabel value="#{bundle.CreateTipoDocumentoLabel_minCreditos}" for="minCreditos" />
                        <p:inputText id="minCreditos" value="#{tipoDocumentoController.selected.minCreditos}" title="#{bundle.CreateTipoDocumentoTitle_minCreditos}" />
                        <p:outputLabel value="#{bundle.CreateTipoDocumentoLabel_correquisitos}" for="correquisitos" />
                        <p:selectOneMenu id="correquisitos" value="#{tipoDocumentoController.selected.correquisitos}" >
                            <f:selectItems value="#{tipoDocumentoController.itemsAvailableSelectOne}"
                                           var="correquisitosItem"
                                           itemValue="#{correquisitosItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{tipoDocumentoController.create}" value="#{bundle.Save}" update="display,:TipoDocumentoListForm:datalist,:growl" oncomplete="handleSubmit(args,'TipoDocumentoCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="TipoDocumentoCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/vistas/tipoDocumento/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="TipoDocumentoEditDlg" widgetVar="TipoDocumentoEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditTipoDocumentoTitle}">
            <h:form id="TipoDocumentoEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{tipoDocumentoController.selected != null}">
                        <p:outputLabel value="#{bundle.EditTipoDocumentoLabel_identificador}" for="identificador" />
                        <p:inputText id="identificador" value="#{tipoDocumentoController.selected.identificador}" title="#{bundle.EditTipoDocumentoTitle_identificador}" required="true" requiredMessage="#{bundle.EditTipoDocumentoRequiredMessage_identificador}"/>
                        <p:outputLabel value="#{bundle.EditTipoDocumentoLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{tipoDocumentoController.selected.nombre}" title="#{bundle.EditTipoDocumentoTitle_nombre}" required="true" requiredMessage="#{bundle.EditTipoDocumentoRequiredMessage_nombre}"/>
                        <p:outputLabel value="#{bundle.EditTipoDocumentoLabel_creditos}" for="creditos" />
                        <p:inputText id="creditos" value="#{tipoDocumentoController.selected.creditos}" title="#{bundle.EditTipoDocumentoTitle_creditos}" required="true" requiredMessage="#{bundle.EditTipoDocumentoRequiredMessage_creditos}"/>
                        <p:outputLabel value="#{bundle.EditTipoDocumentoLabel_maxCreditos}" for="maxCreditos" />
                        <p:inputText id="maxCreditos" value="#{tipoDocumentoController.selected.maxCreditos}" title="#{bundle.EditTipoDocumentoTitle_maxCreditos}" />
                        <p:outputLabel value="#{bundle.EditTipoDocumentoLabel_minCreditos}" for="minCreditos" />
                        <p:inputText id="minCreditos" value="#{tipoDocumentoController.selected.minCreditos}" title="#{bundle.EditTipoDocumentoTitle_minCreditos}" />
                        <p:outputLabel value="#{bundle.EditTipoDocumentoLabel_correquisitos}" for="correquisitos" />
                        <p:selectOneMenu id="correquisitos" value="#{tipoDocumentoController.selected.correquisitos}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{tipoDocumentoController.itemsAvailableSelectOne}"
                                           var="correquisitosItem"
                                           itemValue="#{correquisitosItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{tipoDocumentoController.update}" value="#{bundle.Save}" update="display,:TipoDocumentoListForm:datalist,:growl" oncomplete="handleSubmit(args, 'TipoDocumentoEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="TipoDocumentoEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/vistas/tipoDocumento/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListTipoDocumentoTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="TipoDocumentoListForm">
                <p:panel header="#{bundle.ListTipoDocumentoTitle}">
                    <p:dataTable id="datalist" value="#{tipoDocumentoController.items}" var="item"
                                 selectionMode="single" selection="#{tipoDocumentoController.selected}"
                                 paginator="true"
                                 rowKey="#{item.identificador}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTipoDocumentoTitle_identificador}"/>
                            </f:facet>
                            <h:outputText value="#{item.identificador}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTipoDocumentoTitle_nombre}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombre}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTipoDocumentoTitle_creditos}"/>
                            </f:facet>
                            <h:outputText value="#{item.creditos}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTipoDocumentoTitle_maxCreditos}"/>
                            </f:facet>
                            <h:outputText value="#{item.maxCreditos}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTipoDocumentoTitle_minCreditos}"/>
                            </f:facet>
                            <h:outputText value="#{item.minCreditos}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTipoDocumentoTitle_correquisitos}"/>
                            </f:facet>
                            <h:outputText value="#{item.correquisitos}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{tipoDocumentoController.prepareCreate}" update=":TipoDocumentoCreateForm" oncomplete="PF('TipoDocumentoCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":TipoDocumentoViewForm" oncomplete="PF('TipoDocumentoViewDialog').show()" disabled="#{empty tipoDocumentoController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":TipoDocumentoEditForm" oncomplete="PF('TipoDocumentoEditDialog').show()" disabled="#{empty tipoDocumentoController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{tipoDocumentoController.destroy}" update=":growl,datalist" disabled="#{empty tipoDocumentoController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/vistas/tipoDocumento/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="TipoDocumentoViewDlg" widgetVar="TipoDocumentoViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewTipoDocumentoTitle}">
            <h:form id="TipoDocumentoViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{tipoDocumentoController.selected != null}">
                        <h:outputText value="#{bundle.ViewTipoDocumentoLabel_identificador}"/>
                        <h:outputText value="#{tipoDocumentoController.selected.identificador}" title="#{bundle.ViewTipoDocumentoTitle_identificador}"/>
                        <h:outputText value="#{bundle.ViewTipoDocumentoLabel_nombre}"/>
                        <h:outputText value="#{tipoDocumentoController.selected.nombre}" title="#{bundle.ViewTipoDocumentoTitle_nombre}"/>
                        <h:outputText value="#{bundle.ViewTipoDocumentoLabel_creditos}"/>
                        <h:outputText value="#{tipoDocumentoController.selected.creditos}" title="#{bundle.ViewTipoDocumentoTitle_creditos}"/>
                        <h:outputText value="#{bundle.ViewTipoDocumentoLabel_maxCreditos}"/>
                        <h:outputText value="#{tipoDocumentoController.selected.maxCreditos}" title="#{bundle.ViewTipoDocumentoTitle_maxCreditos}"/>
                        <h:outputText value="#{bundle.ViewTipoDocumentoLabel_minCreditos}"/>
                        <h:outputText value="#{tipoDocumentoController.selected.minCreditos}" title="#{bundle.ViewTipoDocumentoTitle_minCreditos}"/>
                        <h:outputText value="#{bundle.ViewTipoDocumentoLabel_correquisitos}"/>
                        <h:outputText value="#{tipoDocumentoController.selected.correquisitos}" title="#{bundle.ViewTipoDocumentoTitle_correquisitos}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="TipoDocumentoViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>